"""Tests for evidence binding (U6b).

Evidence **addresses** a control, it never **attests** one — that core-principle
regression is asserted here (no ``ce:attests`` triple is ever emitted). Also
covers: the emitted node carries ``ce:contentHash`` + ``CollectionMetadata`` +
``ce:evidentiaryStatus "mock"``; two generators addressing one control both
appear under it in a coverage query; the emitted graph validates against
``ontology/cmmc_shapes.ttl`` (pyshacl).
"""

from __future__ import annotations

from pathlib import Path

from rdflib import Graph, Literal, URIRef

from ontology.prefixes import CE, CMMC, PROV, bind_prefixes
from evidence.binding import (
    CollectionMetadata,
    bind_check_evidence,
    bind_config_evidence,
    bind_evidence,
)
from evidence.generators import GeneratorContext
from evidence.generators.mock_config import MockConfigExportGenerator
from evidence.generators.mock_policy import MockPolicyCheckGenerator

_SHAPES = Path(__file__).resolve().parents[1] / "ontology" / "cmmc_shapes.ttl"


def _new_graph() -> Graph:
    g = Graph()
    bind_prefixes(g)
    return g


def _iam_config_artifact():
    """The IAM config-export artifact (addresses AC.L2-3.1.1)."""
    arts = MockConfigExportGenerator().collect(GeneratorContext(evidence_set="all-covered"))
    return next(a for a in arts if "AC.L2-3.1.1" in a.controls)


def _iam_policy_artifact():
    arts = MockPolicyCheckGenerator().collect(GeneratorContext(evidence_set="all-covered"))
    return next(a for a in arts if "AC.L2-3.1.1" in a.controls)


class TestConfigEvidenceBinding:
    def test_binds_expected_predicates(self):
        g = _new_graph()
        art = _iam_config_artifact()
        ev = bind_config_evidence(g, art)

        assert (ev, RDF_type(), CE.Evidence) in g
        assert (ev, RDF_type(), CE.ConfigExport) in g
        # addresses the right control, never a bare literal
        assert (ev, CE.addresses, CMMC["AC.L2-3.1.1"]) in g
        # a stored content hash (64 hex)
        chash = g.value(ev, CE.contentHash)
        assert chash is not None and len(str(chash)) == 64
        # R12 mock marker
        assert (ev, CE.evidentiaryStatus, Literal("mock")) in g
        # generated by a collection activity
        act = g.value(ev, PROV.wasGeneratedBy)
        assert act is not None

    def test_collection_metadata_on_activity(self):
        g = _new_graph()
        art = _iam_config_artifact()
        ev = bind_config_evidence(g, art)
        act = g.value(ev, PROV.wasGeneratedBy)

        # CollectionMetadata fields land on the activity + collector agent.
        assert g.value(act, CE.sourceSystem) is not None
        assert g.value(act, CE.exportCommand) is not None
        assert g.value(act, CE.collectedAt) is not None
        assert g.value(act, PROV.startedAtTime) is not None
        collector = g.value(act, PROV.wasAssociatedWith)
        assert collector is not None
        assert g.value(collector, CE.collectorVersion) is not None
        # activity is pinned to the CollectEvidence plan step
        step = g.value(act, URIRef("http://purl.org/net/p-plan#correspondsToStep"))
        assert step is not None and str(step).endswith("step-CollectEvidence")

    def test_idempotent_same_content_same_node(self):
        g = _new_graph()
        art = _iam_config_artifact()
        ev1 = bind_config_evidence(g, art)
        ev2 = bind_config_evidence(g, art)
        assert ev1 == ev2

    def test_metadata_dataclass_shape(self):
        md = CollectionMetadata("gcp.iam", "gcloud ...", "2026-07-02T00:00:00Z", "mock-0.1.0")
        assert md.source_system == "gcp.iam"
        assert str(md.collector_uri()).endswith("collector/gcp-iam")


class TestEvidenceNeverAttests:
    def test_no_attests_triple_config(self):
        g = _new_graph()
        bind_config_evidence(g, _iam_config_artifact())
        _assert_addresses_not_attests(g)

    def test_no_attests_triple_policy(self):
        g = _new_graph()
        bind_check_evidence(g, _iam_policy_artifact())
        _assert_addresses_not_attests(g)

    def test_no_attests_across_full_run(self):
        g = _new_graph()
        for art in MockConfigExportGenerator().collect(GeneratorContext()):
            bind_evidence(g, art)
        for art in MockPolicyCheckGenerator().collect(GeneratorContext()):
            bind_evidence(g, art)
        _assert_addresses_not_attests(g)
        # ... and no attestation-only predicates leak in either.
        assert len(list(g.triples((None, CE.hasOutcome, None)))) == 0


class TestCoverageQuery:
    def test_two_generators_appear_under_same_control(self):
        g = _new_graph()
        bind_config_evidence(g, _iam_config_artifact())
        bind_check_evidence(g, _iam_policy_artifact())

        rows = list(g.query(
            "SELECT ?ev WHERE { ?ev ce:addresses ?c }",
            initBindings={"c": CMMC["AC.L2-3.1.1"]},
        ))
        evidence_nodes = {str(r[0]) for r in rows}
        assert len(evidence_nodes) == 2  # ConfigExport + PolicyCheck

        # And the two nodes are distinct RDF types.
        types = set()
        for ev in evidence_nodes:
            for t in g.objects(URIRef(ev), RDF_type()):
                if t in (CE.ConfigExport, CE.PolicyCheck):
                    types.add(t)
        assert types == {CE.ConfigExport, CE.PolicyCheck}


class TestShapeValidation:
    def test_emitted_graph_conforms_to_evidence_shape(self):
        pyshacl = _import_pyshacl()
        if pyshacl is None:
            import pytest
            pytest.skip("pyshacl not available")

        g = _new_graph()
        for art in MockConfigExportGenerator().collect(GeneratorContext()):
            bind_evidence(g, art)
        for art in MockPolicyCheckGenerator().collect(GeneratorContext()):
            bind_evidence(g, art)

        shapes = Graph()
        shapes.parse(str(_SHAPES), format="turtle")
        conforms, _, report = pyshacl.validate(
            g, shacl_graph=shapes, inference="none", advanced=True,
        )
        assert conforms, report


# --- helpers ---------------------------------------------------------------

def RDF_type() -> URIRef:
    return URIRef("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")


def _assert_addresses_not_attests(g: Graph) -> None:
    # There IS at least one addresses edge...
    assert len(list(g.triples((None, CE.addresses, None)))) > 0
    # ...and NEVER an attests edge (core principle).
    assert len(list(g.triples((None, CE.attests, None)))) == 0


def _import_pyshacl():
    try:
        import pyshacl
        return pyshacl
    except Exception:
        return None
